version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-todoapp}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - three-tier-net

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - three-tier-net

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:80
    networks:
      - three-tier-net

networks:
  three-tier-net:

volumes:
  db_data:
