
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-green
  namespace: ms-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
      version: green
  template:
    metadata:
      labels:
        app: booking-service
        version: green
    spec:
      containers:
      - name: booking
        image: REPLACE_REGISTRY/booking-service:latest
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
