
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-blue
  namespace: ms-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
      version: blue
  template:
    metadata:
      labels:
        app: events-service
        version: blue
    spec:
      containers:
      - name: events
        image: REPLACE_REGISTRY/events-service:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
