
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: ms-demo
spec:
  selector:
    app: events-service
    version: blue   # switch this to 'green' to route traffic to green deployment
  ports:
  - port: 80
    targetPort: 5000
